name: the VIVE
favicon: null
layout_spectrum: 0.06286485213786364
typography_spectrum: 0.6436374762561172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf7f4'
    - '#ecdcce'
    - '#c6b8af'
    - '#3a4459'
    - '#949391'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.14986715442501009
  rhythmicContrast: 0.5
purpose: []
